# Generated by Django 5.2.5 on 2025-08-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
